version: "3"
services:
  datasette:
    image: yejiyang/datasette:no-limit-csv-publish-20221223-v7
    ports:
      - "8001:8001"
    volumes:
      - ${PWD}:/mnt
    command: datasette -p 8001 -h 0.0.0.0 /usr/local/data/zeropm-v0-0-4.sqlite -m /usr/local/data/metadata.yml --setting max_csv_mb 0 --template-dir /mnt/templates
